
name: Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Env: GITHUB_REPOSITORY
        run: echo $GITHUB_REPOSITORY
      - name: Print All Env
        run: printenv
